### PR TITLE
Support for PostgreSQL (store, subs)

### PR DESCRIPTION
**Pull request by alexeyzimarev**
Follow-up discussions here https://github.com/Eventuous/eventuous/pull/19, also after looking at SqlStreamStore and the implementation by @claudiuchis.

I am not yet sure what can be reused between different dbs. It seems that `System.Data` abstractions aren't that good as native providers add more async IO optimisations on top, plus they have their own native things like types.

I started by implementing everything inside the Postgres project, and then move some bits to the shared project.

Scripts are largely inspired by SqlStreamStore but aren't that complex. I am unable to figure out the need for their Postgres code that expects only a part of the messages array to be added and then triggers the `enforce_idempotent_append` function. Everything is transactional, how could this happen? Maybe in some crazy scenario, but I don't think it's something I'd want to care about.

Also, I won't do anything to simulate native ESDB features like maxAge and maxCount support, which adds quite a lot of complexity to SqlStreamStore.

### CODE REVIEW

**Comment by claudiuchis** [comment]
I like your event store implementation for Postgres. Very clean. And I believe it's better to keep the sql code in stored proc, the way you've done it. And using a separate table to store the stream metadata also makes sense, as it makes it easier to implement the EventStoreDB like API.

I agree, there is not much code reuse between different dbs for the event store implementation. However, some code could be reused for subscriptions (stream, all streams) where polling can be employed as the default way to retrieve stream changes for all dbs.

Some db's like Postgres provide a way to get notifications on table changes (notify/listen) which can be used instead of polling which reduces the hit on the db. 

However, I found out that it is non-trivial to implement the notify/listen approach as it requires 2 threads (one to get the notifications which is blocking, the other to read the changes from the last checkpoint and notify the subscribers). It also requires one db connection per thread as Npgsql driver does not allow multiple threads to use the same connection.

My implementation of subscriptions for Postgresql is using polling as I got frustrated with getting the notify/listen method working.

**Review by claudiuchis — APPROVED** [review]

**Review by claudiuchis — APPROVED** [review]

**Comment by alexeyzimarev** [comment]
I thought about notifications, but I'll do the polling first, as you did. The issue with change streams and notifications is that you first need to read the history, and then switch to notifications, but how do you know the exact moment to switch? Assuming the polling query returned zero results, we switch to real-time notifications, but how can we be sure that nothing was added at that exact moment? So, we'd need to subscribe to notifications when the polling query returned no result, but have a transition stage when notifications are put in the queue, execute a polling query again to ensure there are no messages in between, and then start processing the queue. It is quite a complex process, so I'd prefer not to implement it right now.

My main goal with Postgres support is to try Amazon Aurora Serverless, and they advise against using LISTEN/NOTIFY (I understand why), one more argument for not doing it atm.

I agree that some code will be shared, that's why I added the `Sql.Base` project. I just want to find similarities when building another one, like SQLite or MySQL.

**Comment by claudiuchis** [comment]
I haven't thought about the events that would be added during the transition from reading the history to using notifications. I thought that using the checkpoint with notifications would pick those events as well, but while they will be picked no doubt, there could be a delay until the first notification kicks in. So, the question is whether that delay is acceptable or not.

Using a serverless SQL-like db to do event sourcing was the main problem I tried to solve in my case to save money, as I didn't want to run a db in the cloud continously for my pet projects. I thought event sourcing can be done with any type of storage as it's append only. As I found out, that was true until I got to implement subscriptions. That was the moment I realized the true power of EventStoreDB.

Doing polling on a serverless db would keep it running when there is no other db activity which defeats the purpose of running a serverless db. The workaround would be to decrease the polling frequency when there is no data fetched, but to make any difference on running costs it would need to delay polling something like 5 or 10 minutes or more, but then would that delay be acceptable for the application (for read models and reactions)?. So, it's easy to get down this rabbit hole, unless you have a better trick up your sleeve.

**Comment by alexeyzimarev** [comment]
My idea here is that for smaller, less frequently used workloads, you'd have an application that implements some bounded context, where both command and query sides are in the same workload. Imagine this workload is a lambda with 30 sec timeout. Then, when the command is executed, the database spins up as we read an aggregate from the store. If executing the command we appended any events, the polling subscription should pick it up within some milliseconds, and do the projection job or/and publish an integration event to something like SNS. Then, the function will terminate on timeout as for a lambda function the timeout is counted from the function invocation. As long as we don't receive any more commands, the lambda will be terminated, even if it keeps polling the db. After some time, the database will also scale down to zero. That's basically the idea.

**Comment by claudiuchis** [comment]
That makes sense.

**Comment by alexeyzimarev** [comment]
Partial fix for https://github.com/Eventuous/eventuous/issues/96

**Pull request merged**
