### PR TITLE
Update postgres to be compatible with Npgsql 7

### LINKED ISSUE #182: Eventuous breaks with npgsql >= 7.0.0
When trying to use the Postgres event store along with npgsql >= 7.0.0 it breaks with the following exception:

```
Npgsql.PostgresException (0x80004005): 42883: procedure eventuous.read_all_forwards(_from_position => bigint, _count => integer) does not exist
```

The workaround is to put the following code somewhere (I put it above the `services.AddAggregateStore<PostgresStore>();`):
```
AppContext.SetSwitch("Npgsql.EnableStoredProcedureCompatMode", true);
```

The real solution would probably be something like rewriting this (and other similar methods):
https://github.com/Eventuous/eventuous/blob/b4f1af73d3d2b82f29c2fac50c286b2a9677f28d/src/Postgres/src/Eventuous.Postgresql/Subscriptions/PostgresAllStreamSubscription.cs#L24-L31
into just using the recommended plain method which is `SELECT * FROM function_name($1,$2)` 

Source: https://www.npgsql.org/doc/release-notes/7.0.html#a-namecommandtypestoredprocedure-commandtypestoredprocedure-now-invokes-procedures-instead-of-functions

Another issue is that connections to the database are not reused/not closed which is probably related to the new `DbDataSource` way of connecting: https://www.npgsql.org/doc/release-notes/7.0.html#dbdatasource

### PR DESCRIPTION
**Pull request by fbjerggaard**
Fixes #182

Currently a WIP. Tests works when running them individually but fails when run simultaneously. 

Probably something to do with the scope of the Faker library, will look into it.

### CODE REVIEW

**Comment by alexeyzimarev** [comment]
What happens when the test fails? Could it be related to https://github.com/Eventuous/eventuous/issues/181?

**Comment by fbjerggaard** [comment]
It could very well be related. The issue is that it calls the `append_events` function with the messages parameter being a schema from another test

**Comment by fbjerggaard** [comment]
The exact error is this:

```
    Npgsql.PostgresException : 42883: function karlee_wunsch27.append_events(character varying, integer, timestamp with time zone, deja_kuhn46.stream_message[]) does not exist
```
Note the different schema names

**Comment by alexeyzimarev** [comment]
Right, I assume I never expected two different schemas to be used in one app :)

**Comment by fbjerggaard** [comment]
Understandably :) It must be some parallellism with Xunit that breaks it.

I have now tested the code in my project, and so far everything works as expected. I am not entirely happy with the DI registration stuff since it is a bit.. funky to setup now. It currently requires this in the registrations:

```
NpgsqlDataSourceBuilder GetConnection() => new(configuration.GetConnectionString("EventDatabase"));
services.AddSingleton((NpgsqlDataSourceBuilder)GetConnection());
services.AddSingleton((GetPostgresConnection)GetConnection().Build().CreateConnection);
services.AddSingleton(new PostgresStoreOptions());
services.AddAggregateStore<PostgresStore>();
```

I am working on optimizing that

**Comment by fbjerggaard** [comment]
I have come a little closer to figuring out the issue with the failing test.

It will always be either one of `SubscribeToAll.ShouldConsumeProducedEvents` or `SubscribeToStream.ShouldConsumeProducedEvents` that fails.

The `SchemaName` used for the `stream_message` in the test failing is always the one from the test that runs successfully.

I don't have enough knowledge about Xunit to figure out what is going wrong

**Comment by alexeyzimarev** [comment]
It's because the `IntegrationFixture` instance is static:

```
    public static IntegrationFixture Instance { get; } = new();
```

So the schema name is shared. It is like that to decrease the setup time by doing it only once.

**Comment by alexeyzimarev** [comment]
There's also this:

```csharp
    public async Task InitializeAsync() {
        await _schema.CreateSchema(Instance.GetConnection);
        if (_autoStart) await Start();
    }

    public async Task DisposeAsync() {
        if (_autoStart) await Stop();
        _listener.Dispose();
    }
```

Maybe it's a good idea to add schema drop when stopping. But it will make test longer to run, maybe not that much though.

**Comment by alexeyzimarev** [comment]
I fixed the conflicting tests issue in my big PR

**Pull request closed without merging**
